matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      sudo: required
      language: swift

before_install:
  - swift package generate-xcodeproj

script:
  - xcodebuild -project Inflect.xcodeproj -scheme "Inflect-Package" -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test | xcpretty
  - xcodebuild -project Inflect.xcodeproj -scheme "Inflect-Package" -enableCodeCoverage YES build-for-testing test | xcpretty
  - xcodebuild -project Inflect.xcodeproj -scheme "Inflect-Package" -enableCodeCoverage YES -destination "platform=tvOS Simulator,name=Apple TV" build-for-testing test | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
